name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create cards
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: ThaiNguyenGiaBao/PNG/blob/main/getData@v1
        with:
          org-name: "TickLabVN"
          token: ${{ secrets.PERSONAL_TOKEN }}
        env:
          token: ${{ secrets.PERSONAL_TOKEN }}
