name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run
        uses: TranLam2004/ORG_STAT@v1
        with:
          orgname: "TickLabVN"
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}


